services:
  envoy:
    image: envoyproxy/envoy:v1.26-latest
    hostname: envoy
    ports:
      - "18000:18000"
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
      - ./plugin.wasm:/etc/envoy/proxy-wasm-plugins/plugin.wasm
    networks:
      - envoymesh
networks:
  envoymesh: {}